drums_practice_logs/drums_practice_logs/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('practice_logs.urls')),
    path('users/', include('users.urls'))
]

drums_practice_logs/practice_logs/urls.py
from django.urls import path
from . import views

app_name = "practice_logs"

urlpatterns = [
    path("", views.index, name="index"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("sources/view_sources", views.view_sources, name="view_sources"),
    path("sources/new_source", views.new_source, name="new_source"),
    path("sources/edit_source/<int:source_id>/", views.edit_source, name="edit_source"),
    path("sources/delete_source/<int:source_id>/", views.delete_source, name="delete_source"),
    path("sources/new_print_exercise", views.new_print_exercise, name="new_print_exercise"),
    path("sources/new_online_exercise", views.new_online_exercise, name="new_online_exercise"),
    path("sources/edit_print_exercise/<int:exercise_id>/", views.edit_print_exercise, name="edit_print_exercise"),
    path("sources/edit_online_exercise/<int:exercise_id>/", views.edit_online_exercise, name="edit_online_exercise"),
    path("sources/delete_exercise/<int:exercise_id>/", views.delete_exercise, name="delete_exercise"),
    path("sessions/view_sessions", views.view_sessions, name="view_sessions"),
    path("sessions/new_session", views.new_session, name="new_session"),
    path("sessions/edit_session/<int:session_id>/", views.edit_session, name="edit_session"),
    path("sessions/delete_session/<int:session_id>/", views.delete_session, name="delete_session"),
    path("goals/view_goals", views.view_goals, name="view_goals"),
    path("goals/new_goals", views.new_goal, name="new_goal"),
    path("goals/delete_goals/<int:goal_id>/", views.delete_goal, name="delete_goal"),
]

drums_practice_logs/users/urls.py
from django.urls import path, include
from . import views

app_name = "users"

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("signup/", views.sign_up, name="sign_up")
]

drums_practice_logs/practice_logs/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError
from datetime import datetime as dt, timedelta
from django.contrib.auth.models import User


class Source(models.Model):
    SOURCE_TYPES = [
        ("book", "Book"),
        ("online_platform", "Online Platform"),
        ("online_article", "Online Article"),
        ("video_guide", "Video Guide"),
        ("other", "Other")
    ]
    
    name = models.CharField(max_length=100)
    type = models.CharField(choices=SOURCE_TYPES, max_length=15)
    author = models.CharField(max_length=30)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        unique_together = [["name", "user"]]

class Exercise(models.Model):
    name = models.CharField(max_length=200)
    source = models.ForeignKey(Source, on_delete=models.CASCADE)
    page = models.IntegerField(default=1, blank=True, null=True)
    link = models.URLField(blank=True, null=True)
    times_practiced = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
    class Meta:
        unique_together = [["name", "source"]]

class Session(models.Model):
    date = models.DateField(auto_now_add=False, default=dt.today, 
                            validators=[MaxValueValidator(dt.today().date(), message=f"Please choose a day on or before today")])
    time_minutes = models.IntegerField(validators=[MinValueValidator(1)])
    exercises = models.ManyToManyField(Exercise, through="SessionExercise")
    days_since_last_practice = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
class SessionExercise(models.Model):
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    bpm = models.PositiveIntegerField()
    
class Goal(models.Model):
    PERIODS = [
        ("Weekly", "Weekly"),
        ("Biweekly", "Biweekly"),
        ("Monthly", "Monthly"),
    ]
    
    STATUS = [
        ("complete", "Completed"),
        ("in_progress", "In Progress"),
        ("expired", "Expired")
    ]
    
    date_validation_msg = "End date must be between a week and a month after the start date"
    
    start_date = models.DateField(auto_now_add=False, default=dt.today)
    end_date = models.DateField(auto_now_add=False, default=dt.today)
    frequency = models.IntegerField(default=1)
    period = models.CharField(choices=PERIODS, max_length=8)
    exercise = models.ForeignKey(Exercise, on_delete=models.SET_DEFAULT, default="", blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    progress = models.DecimalField(max_digits=5, decimal_places=4, default=0, validators=[MinValueValidator(0), MaxValueValidator(1)])
    status = models.CharField(choices=STATUS, max_length=11, default="in_progress")
    
    def clean(self):
        start_date = self.start_date
        end_date = self.end_date
        if not end_date >= start_date + timedelta(days=7):
            raise ValidationError("End date must be at least 1 week after start date")
        elif end_date > start_date + timedelta(days=31):
            raise ValidationError("End date cannot be more than 1 month after start date")
        
    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

drums_practice_logs/practice_logs/views.py
from django.shortcuts import render, redirect
from .models import Source, Exercise, Session, SessionExercise, Goal
from .forms import SessionForm, DateSearchForm, SourceForm, PrintExerciseForm, \
    OnlineExerciseForm, GoalsForm, NewSessionExerciseFormSet, EditSessionExerciseFormSet
from datetime import datetime as dt, date, timedelta
import calendar
import pandas as pd
import matplotlib.pyplot as plt
from io import BytesIO
import urllib, base64
from django.contrib.auth.decorators import login_required
from django.http import Http404
import logging
import sys

default_start_date = dt.today() - timedelta(days=30)
default_end_date = dt.today()


logger = logging.getLogger('neo-get-data')
logger.setLevel(logging.INFO)
ch = logging.StreamHandler(stream=sys.stdout)
ch.setLevel(logging.INFO)
formatter = logging.Formatter('%(asctime)s %(levelname)s: %(message)s')
ch.setFormatter(formatter)
logger.addHandler(ch)


def index(request):
    return render(request, "practice_logs/index.html")

@login_required
def new_session(request):
    if request.method == "POST":
        form = SessionForm(request.user, request.POST)
        formset = NewSessionExerciseFormSet(request.POST, form_kwargs={"user": request.user})
        if form.is_valid() and formset.is_valid():
            session = form.save(commit=False)
            session.user = request.user
            if session.user != request.user:
                raise Http404
            formset.instance = session
            session.save()
            formset.save()
            return redirect("practice_logs:view_sessions")
    else:
        form = SessionForm(request.user)
        formset = NewSessionExerciseFormSet(queryset=SessionExercise.objects.none(), form_kwargs={"user": request.user})
        
    context = {
        "form": form,
        "formset": formset
    }
    return render(request, "practice_logs/new_session.html", context)

@login_required
def view_sessions(request, start_date=default_start_date.strftime("%Y-%m-%d"), end_date=default_end_date.strftime("%Y-%m-%d")):
    # Date Form
    if request.method == "POST":
        form = DateSearchForm(data=request.POST)
        start_date = f"{form.data['start_date']}"
        end_date = f"{form.data['end_date']}"
    else:
        form = DateSearchForm()
    
    # Get fields
    fields = ['Date', 'Time (Minutes)', 'Exercises', 'BPM', 'Days Since Last Practice']
    
    # Session Data
    session_data = Session.objects.filter(date__range=[start_date, end_date], user=request.user).values('id', 'date', 'time_minutes',
                                                                                     'days_since_last_practice').order_by('-date')
    session_ids = [session['id'] for session in session_data]
    
    # Get exercise name and BPM data
    session_exercises = SessionExercise.objects.filter(session__in=session_ids).values()
    for session in session_exercises:
            session['exercise_id'] = Exercise.objects.get(id=session['exercise_id']).name
        
    context = {
        "session_data": session_data,
        "session_exercises": session_exercises,
        "fields": fields,
        "form": form,
        "start_date": start_date,
        "end_date": end_date
    }
    
    return render(request, "practice_logs/view_sessions.html", context)

@login_required
def edit_session(request, session_id):
    session = Session.objects.get(id=session_id)
    session_exercises = SessionExercise.objects.filter(session_id=session.id)
    
    if session.user != request.user:
        raise Http404
    
    if request.method == "POST":
        form = SessionForm(request.user, instance=session, data=request.POST)
        formset = EditSessionExerciseFormSet(request.POST, form_kwargs={"user": request.user})
        if form.is_valid() and formset.is_valid():
            session = form.save(commit=False)
            exercises = formset.save(commit=False)
            for exercise in exercises:
                exercise.session = session
                exercise.save()
            session.save()
            formset.save()
            return redirect("practice_logs:view_sessions")
    else:
        form = SessionForm(request.user, instance=session)
        formset = EditSessionExerciseFormSet(queryset=session_exercises, form_kwargs={"user": request.user})
        
    context = {"form": form, "session": session, "formset": formset}
    return render(request, "practice_logs/edit_sessions.html", context)

@login_required
def delete_session(request, session_id):
    session = Session.objects.get(id=session_id)
    
    if session.user != request.user:
        raise Http404
    
    session.delete()
    return redirect("practice_logs:view_sessions")

@login_required
def dashboard(request):
    session_data = pd.DataFrame(list(Session.objects.filter(
        date__range=[dt.today() - timedelta(days=30), dt.today()], user=request.user).values()))
    
    # Return empty dashboard if user does not have enough session data available
    if len(session_data) < 2:
        context = {
            'session_data': session_data
        }
        return render(request, "practice_logs/dashboard.html", context)
    
    # Dashboard data             
    curr_month = dt.strftime(dt.today(), "%Y-%m")
    days_of_month = calendar.monthrange(int(curr_month[0:4]),int(curr_month[5:]))[1]
    first_day_of_month = f"{curr_month}-01"
    last_day_of_month = f"{curr_month}-{days_of_month}"

    session_data_monthly = Session.objects.filter(date__range=[first_day_of_month, last_day_of_month], user=request.user).values()
    days_practiced_curr_month =  len(pd.DataFrame(list(session_data_monthly)).groupby('date', as_index=False)) if len(session_data_monthly) > 0 else 0
    average_practice_time = round(session_data.groupby('date', as_index=False).sum()["time_minutes"].mean())
    avg_days_between_practice = round(session_data.groupby('date', as_index=False).mean()["days_since_last_practice"].mean())
    days_since_last_practice = (date.today() - session_data['date'].max()).days
    
    # Consistency Chart
    consistency = session_data.groupby('date', as_index=False).min()
    
    plt.figure(figsize=(18, 8))
    plt.xlabel('Practice Date', fontsize=20)
    plt.ylabel('Number of Days', fontsize=20)
    plt.title("Days Since Last Practice Session", fontsize=30)
    plt.plot(consistency['date'], consistency['days_since_last_practice'])
    
    plt.gca().set_facecolor("#eff0f8")
    consistency_chart = plt.gcf()
    consistency_chart.set_facecolor("#cee2e7")
    buffer = BytesIO()
    consistency_chart.savefig(buffer, format="png")
    buffer.seek(0)
    consistency_chart_string = base64.b64encode(buffer.read())
    consistency_chart_uri = urllib.parse.quote(consistency_chart_string)
    
    # Duration Chart    
    practice_times = session_data[['date', 'time_minutes']].groupby('date', as_index=False).sum()
    average_practice_time_line = pd.DataFrame(data={'average': practice_times['time_minutes'].mean()}, index=range(0, practice_times.shape[0]))

    plt.figure(figsize=(18, 8))
    plt.xlabel("Practice Date", fontsize=20)
    plt.ylabel("Total Practice Time", fontsize=20)
    plt.title("Total Practice Time per Date", fontsize=30)
    plt.plot(practice_times['date'], practice_times['time_minutes'])
    plt.plot(practice_times['date'], average_practice_time_line)
    
    plt.gca().set_facecolor("#eff0f8")
    duration_chart = plt.gcf()
    duration_chart.set_facecolor("#cee2e7")
    buffer = BytesIO()
    duration_chart.savefig(buffer, format="png")
    buffer.seek(0)
    duration_chart_string = base64.b64encode(buffer.read())
    duration_chart_uri = urllib.parse.quote(duration_chart_string)
    
    context = {
        'consistency_chart': consistency_chart_uri,
        'duration_chart': duration_chart_uri,
        'days_practiced_curr_month': days_practiced_curr_month,
        'average_practice_time': average_practice_time,
        'avg_days_between_practice': avg_days_between_practice,
        'session_data': session_data,
        'days_since_last_practice': days_since_last_practice
    }
    
    return render(request, "practice_logs/dashboard.html", context)

@login_required
def view_sources(request):
    sources = Source.objects.filter(user=request.user)
    online_sources = sources.exclude(type="book").values()
    print_sources = sources.filter(type="book").values()
    online_source_ids = [source["id"] for source in online_sources]
    print_source_ids = [source["id"] for source in print_sources]
    online_exercises = Exercise.objects.filter(source_id__in=online_source_ids).values()
    print_exercises = Exercise.objects.filter(source_id__in=print_source_ids).values()

    context = {
        'sources': list(sources),
        'online_sources': online_sources,
        'print_sources': print_sources,
        'online_exercises': online_exercises,
        'print_exercises': print_exercises
    }
    
    return render(request, "practice_logs/view_sources.html", context)

@login_required
def new_source(request):
    if request.method == "POST":
        form = SourceForm(data=request.POST)
        if form.is_valid():
            new_source = form.save(commit=False)
            new_source.user = request.user
            new_source.save()
            return redirect("practice_logs:view_sources")
    else:
        form = SourceForm()
    context = {"form": form}
    return render(request, "practice_logs/new_source.html", context)

@login_required
def edit_source(request, source_id):
    source = Source.objects.get(id=source_id)
    
    if source.user != request.user:
        raise Http404
    
    if request.method == "POST":
        form = SourceForm(instance=source, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("practice_logs:view_sources")
    else:
        form = SourceForm(instance=source)
        
    context = {"form": form, "source": source}

drums_practice_logs/practice_logs/templates/practice_logs/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Drums Practice Logs</title>
    <link rel="stylesheet" href="{% static 'practice_logs/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'practice_logs/style.css' %}">
    <link rel="stylesheet" href="{% static 'practice_logs/tables.css' %}">
    <link rel="stylesheet" href="{% static 'practice_logs/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'practice_logs/goals.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script> 
</head>
<body>
    <nav>
        <ul class="navbar-link-list">
            <li>
                <span class="material-symbols-outlined home-button">
                    <a class="navbar-link" href="{% url 'practice_logs:index' %}">home</a>
                </span>
            </li>
            <li>
                <a class="navbar-link" href="{% url 'practice_logs:dashboard' %}">Dashboard</a>
            </li>
            <li>
                <a class="navbar-link" href="{% url 'practice_logs:view_sessions' %}">Sessions</a>
            </li>
            <li>
                <a class="navbar-link" href="{% url 'practice_logs:view_sources' %}">Learning Sources / Exercises</a>
            </li>
            <li>
                <a class="navbar-link" href="{% url 'practice_logs:view_goals' %}">Goals</a>
            </li>
        </ul>
        <ul class="navbar-link-list">
            {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'users:logout' %}">Log Out</a></li>
            {% else %}
            <li><a class="navbar-link" href="{% url 'users:sign_up' %}">Sign Up</a></li>
            <li><a class="navbar-link" href="{% url 'users:login' %}">Log In</a></li>
            {% endif %}
        </ul>
    </nav>
    <main>
        {% block content %}{% endblock content %}
    </main>
</body>
</html>

drums_practice_logs/practice_logs/templates/practice_logs/edit_online_exercise.html
{% extends "practice_logs/base.html" %}

{% block content %}
<div class="item-form-container">
    <h2>Edit Exercise</h2>
    <form action="{% url 'practice_logs:edit_online_exercise' exercise.id %}" method="post" class="item-form">
        {% csrf_token %}
        {{ form.as_table }}
        <div class="item-form-options">
            <button type="submit" class="basic-button">Submit</button>
            <a class="basic-button" href="{% url 'practice_logs:view_sources' %}">Cancel</a>
            <a class="basic-button" href="{% url 'practice_logs:delete_exercise' exercise.id %}">Delete Exercise</a>
        </div>
    </form>
</div>
{% endblock content %}

drums_practice_logs/practice_logs/templates/practice_logs/edit_sessions.html
{% extends "practice_logs/base.html" %}

{% block content %}
<div class="item-form-container">
    <h2>Edit Session</h2>
    <form action="{% url 'practice_logs:edit_session' session.id %}" method="post" class="item-form">
        {% csrf_token %}
        {{ form.as_table }}
        <fieldset>
            <legend>Add up to five exercises to this session:</legend>
            {{ formset.management_form }}
            <div id="session-exercises">
                <div id="session-exercises-labels">
                    <label>Exercise</label>
                    <label>BPM</label>
                </div>
                {% for form in formset.forms %}
                <div class="exercise-form">
                    {{ form.exercise }}
                    {{ form.bpm }}
                    {% for hidden_field in form.hidden_fields %}
                        {{ hidden_field }}
                    {% endfor %}
                    {{ form.DELETE }}
                    {% if form.errors %}
                    <p>The following errors have been found in this exercise:</p>
                        {{ form.errors }}
                    {% endif %}
                </div>
                {% endfor %}
            </div>
        </fieldset>
        <div class="item-form-options">
            <button type="submit" class="basic-button">Submit</button>
            <a class="basic-button" href="{% url 'practice_logs:view_sessions' %}">Cancel</a>
            <a class="basic-button" href="{% url 'practice_logs:delete_session' session.id %}">Delete Session</a>
        </div>
    </form>
    <script type="text/javascript">
        $(document).ready(() => {
            $('input[type="checkbox"]').each(function(index) {
                $(this).after(`<label for="${$(this).attr('id')}" class="checkbox-label"></label>`);
            });
        });
    </script>
</div>
{% endblock content %}

drums_practice_logs/practice_logs/templates/practice_logs/edit_source.html
{% extends "practice_logs/base.html" %}

{% block content %}
<div class="item-form-container">
    <h2>Edit Source</h2>
    <form action="{% url 'practice_logs:edit_source' source.id %}" method="post" class="item-form">
        {% csrf_token %}
        {{ form.as_table }}
        <div class="item-form-options">
            <button type="submit" class="basic-button">Submit</button>
            <a class="basic-button" href="{% url 'practice_logs:view_sources' %}">Cancel</a>
            <a class="basic-button" href="{% url 'practice_logs:delete_source' source.id %}">Delete Source</a>
        </div>
    </form>
</div>
{% endblock content %}

drums_practice_logs/practice_logs/templates/practice_logs/index.html
{% extends "practice_logs/base.html" %}
{% block content %}
<div class="welcome">
    <div>
        <p class="welcome-title">Welcome to the Drums Practice Logs!</p>
        <p class="welcome-text">With this tool, you'll be able to keep track of your habits and ensure that you can practice consistently. Every step is a win!</p>
    </div>
    <div class="welcome-menu">
    {% if user.is_authenticated %}
        <a class="basic-button" href="{% url 'practice_logs:dashboard' %}">Practice Dashboard</a>
        <a class="basic-button" href="{% url 'practice_logs:view_sessions' %}">Session History</a>
    {% else %}
        <a class="basic-button" href="{% url 'users:sign_up' %}">Sign Up</a>
        <a class="basic-button" href="{% url 'users:login' %}">Log In</a>
    {% endif %}
    </div>
</div>
{% endblock content %}

drums_practice_logs/practice_logs/templates/practice_logs/new_goal.html
{% extends "practice_logs/base.html" %}

{% block content %}
<div class="item-form-container" >
    <h2>Add New Goal</h2>
    <form action="{% url 'practice_logs:new_goal' %}" method="post" class="item-form">
        {% csrf_token %}
        {{ form.as_table }}
        <div class="item-form-options">
            <button name="submit" class="basic-button">Add Goal</button>
            <a class="basic-button" href="{% url 'practice_logs:view_goals' %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}

drums_practice_logs/practice_logs/templates/practice_logs/new_online_exercise.html
{% extends "practice_logs/base.html" %}

{% block content %}
<div class="item-form-container">
    <h2>Add New Exercise</h2>
    <form action="{% url 'practice_logs:new_online_exercise' %}" method="post" class="item-form">
        {% csrf_token %}
        {{ form.as_table }}
        <div class="item-form-options">
            <button name="submit" class="basic-button">Add Exercise</button>
            <a class="basic-button" href="/sources/view_sources">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}

drums_practice_logs/practice_logs/templates/practice_logs/new_print_exercise.html
{% extends "practice_logs/base.html" %}

{% block content %}
<div class="item-form-container">
    <h2>Add New Exercise</h2>
    <form action="{% url 'practice_logs:new_print_exercise' %}" method="post" class="item-form">
        {% csrf_token %}
        {{ form.as_table }}
        <div class="item-form-options">
            <button name="submit" class="basic-button">Add Exercise</button>
            <a class="basic-button" href="/sources/view_sources">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}

drums_practice_logs/practice_logs/templates/practice_logs/view_sessions.html
{% extends "practice_logs/base.html" %}

{% block content %}
<div class="sessions">
    <div class="date-search-container">
        <form action="{% url 'practice_logs:view_sessions' %}" class="date-selector" method="post">
            {% csrf_token %}
            {{ form.as_table }}
            <button type="submit" class="session-table-options">Search</button>
        </form>
        <a class="session-table-options" href="{% url 'practice_logs:view_sessions' %}">View Last 30 Days</a>
        <a class="session-table-options" href="{% url 'practice_logs:new_session' %}">Add Session</a>
    </div>
    {% if session_data|length == 0 %}
    <p><strong>No records were found for the given date range.</strong></p>
    {% else %}
    <h2>Session history for the time period of {{ start_date }} to {{ end_date }}</h2>
    <table class="session-history">
        <thead>
            <tr>
                {% for field in fields %}
                    <th>{{ field }}</th>
                {% endfor %}
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for session in session_data %}
                <tr class="session-row">
                    <td class="session-data">{{ session.date }}</td>
                    <td class="session-data session-data-align-center">{{ session.time_minutes }}</td>
                    <td class="session-data">
                    {% for session_exercise in session_exercises %}
                        {% if session_exercise.session_id == session.id %}
                            {{ session_exercise.exercise_id }}
                            <br>                        
                        {% endif %}
                    {% endfor %}
                    </td>
                    <td class="session-data session-data-align-center">
                    {% for session_exercise in session_exercises %}
                        {% if session_exercise.session_id == session.id %}
                            {{ session_exercise.bpm }}
                            <br>                        
                        {% endif %}
                    {% endfor %}
                    </td>
                    <td class="session-data session-data-align-center">{{ session.days_since_last_practice }}</td>
                    <td class="edit-icon session-data"><a href="{% url 'practice_logs:edit_session' session.id %}"><span class="material-symbols-outlined">edit</span></a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
</div>
<script type="text/javascript">
    $(document).ready(() => {
        $('#id_start_date').attr('value', '{{ start_date }}');
        $('#id_end_date').attr('value', '{{ end_date }}');
    });
</script>
{% endblock content %}

drums_practice_logs/practice_logs/templates/practice_logs/view_sources.html
{% extends "practice_logs/base.html" %}

{% block content %}
<div id="sources-exercises-content">
<div class="sources-table-container">
{% if sources|length != 0 %}
<table class="sources-exercises-table">
    <caption class="sources-exercises-table-title">Sources</caption>
    <thead>
        <tr>
            <th>Source Name</th>
            <th>Author</th>
            <th>Type</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for source in sources %}
        <tr>
            <td>{{ source.name }}</td>
            <td>{{ source.author }}</td>
            <td>{{ source.get_type_display }}</td>
            <td class="edit-icon"><a href="{% url 'practice_logs:edit_source' source.id %}"><span class="material-symbols-outlined">edit</span></a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<a class="basic-button source-exercise-button" href="{% url 'practice_logs:new_source' %}"><span class="material-symbols-outlined">add</span>Add New</a>

{% if online_exercises|length == 0 %}
    <p class="sources-exercises-table-title">Exercises (Online Sources)</p>
    <p>No entries available</p>
{% else %}
<table class="sources-exercises-table">
    <caption class="sources-exercises-table-title">Exercises (Online Sources)</caption>
    <thead>
        <tr>
            <th>Exercise Name</th>
            <th>Source</th>
            <th>Link</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for source in sources %}
        {% for exercise in online_exercises %}
        {% if source.id == exercise.source_id %}
            <tr>
                <td>{{ exercise.name }}</td>
                <td>{{ source.name }}</td>
                <td><a href="{{ exercise.link }}" target="_blank">{{ exercise.link }}</a></td>
                <td class="edit-icon"><a href="{% url 'practice_logs:edit_online_exercise' exercise.id %}"><span class="material-symbols-outlined">edit</span></a></td>
            </tr>
        {% endif %}
        {% endfor %}
        {% endfor %}
    </tbody>
</table>
{% endif %}
<a class="basic-button source-exercise-button" href="{% url 'practice_logs:new_online_exercise' %}"><span class="material-symbols-outlined">add</span>Add New</a>

{% if print_exercises|length == 0 %}
    <p class="sources-exercises-table-title">Exercises (Print Sources)</p>
    <p>No entries available</p>
{% else %}
<table class="sources-exercises-table">
    <caption class="sources-exercises-table-title">Exercises (Print Sources)</caption>
    <thead>
        <tr>
            <th>Exercise Name</th>
            <th>Source</th>
            <th>Page</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for source in sources %}
        {% for exercise in print_exercises %}
        {% if source.id == exercise.source_id %}
            <tr>
                <td>{{ exercise.name }}</td>
                <td>{{ source.name }}</td>
                <td>{{ exercise.page }}</td>
                <td class="edit-icon"><a href="{% url 'practice_logs:edit_print_exercise' exercise.id %}"><span class="material-symbols-outlined">edit</span></a></td>
            </tr>
        {% endif %}
        {% endfor %}
        {% endfor %}
    </tbody>
</table>
{% endif %}
<a class="basic-button source-exercise-button" href="{% url 'practice_logs:new_print_exercise' %}"><span class="material-symbols-outlined">add</span>Add New</a>

{% else %}
<a class="basic-button" href="{% url 'practice_logs:new_source' %}">Add New Source</a>
{% endif %}
</div>
{% endblock content %}